# Generated by Django 6.0.5 on 2026-05-13 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('convention', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(choices=[('INT', 'International'), ('CA', 'Canada'), ('US', 'États-Unis')], max_length=3)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2)),
                ('url', models.URLField(blank=True)),
                ('doc_type', models.CharField(choices=[('convention', 'Convention'), ('loi', 'Loi'), ('guide', 'Guide'), ('liste', 'Liste'), ('avis', 'Avis aux navigateurs'), ('autre', 'Autre')], max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
